# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, qustodio-main ]
  pull_request:
    branches: [ master, qustodio-main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install develop tools
        run: | 
          python -m pip install --upgrade pip
          pip install boto3
          brew install make automake autoconf libtool pkg-config gcc
      - name: Install Yarn
        run: npm install -g yarn
      - name: Yarn Install
        run: yarn install
      - name: Run tests
        run: yarn test

